# FGT-02 - Configuración sanitizada
# FortiOS 7.0.3 build 0237
# Secrets, PSK y passwords omitidos deliberadamente.

config vpn ipsec phase1-interface
    edit "INFRA2-IPSEC"
        set type dynamic
        set interface "port1"
        set mode aggressive
        set peertype any
        set net-device disable
        set mode-cfg enable
        set proposal des-md5 des-sha1
        set dhgrp 5 14
        set wizard-type dialup-forticlient
        set xauthtype auto
        set authusrgrp "SSLVPN-USERS"
        set ipv4-start-ip 10.31.60.10
        set ipv4-end-ip 10.31.60.20
        set ipv4-netmask 255.255.255.0
        set dns-mode auto
        set ipv4-split-include "INFRA2-IPSEC_split"
        # set psksecret <REDACTED>
    next
end

config vpn ipsec phase2-interface
    edit "INFRA2-IPSEC"
        set phase1name "INFRA2-IPSEC"
        set proposal des-md5 des-sha1
    next
end

# Objetos principales
# HOST-JUMP01     = 10.31.40.2/32
# HOST-WEB-CAJA  = 10.31.50.2/32
# INFRA2-IPSEC_range = pool generado por el VPN Wizard

# Resumen de políticas
#
# 1) JUMP-TO-WEB
#    incoming: JUMP-LAN (port3)
#    outgoing: WEB-LAN (port4)
#    source: HOST-JUMP01
#    destination: HOST-WEB-CAJA
#    services: HTTPS, RDP, SSH
#    action: ACCEPT
#    NAT: disabled
#    logging: all sessions
#
# 2) USERS-DENY-WEB
#    incoming: VLAN10-USERS
#    outgoing: WEB-LAN (port4)
#    source: NET-USERS-INFRA2
#    destination: HOST-WEB-CAJA
#    service: ALL
#    action: DENY
#    logging: all
#
# 3) vpn_INFRA2-IPSEC_remote_0
#    incoming: INFRA2-IPSEC
#    outgoing: JUMP-LAN (port3)
#    source: INFRA2-IPSEC_range
#    destination: HOST-JUMP01
#    service: RDP
#    action: ACCEPT
#    NAT: disabled
#    logging: all sessions
